package org.pathwayeditor.notations.sbgnpd.ndom.parser;

import org.pathwayeditor.businessobjects.drawingprimitives.IDrawingElement;


public interface IToken {

	enum TreeTokenType { NODE_ROOT, EDGE_ROOT, COMPARTMENT, MACROMOLECULE, COMPLEX,
		NA_FEATURE, SIMPLE_CHEMICAL, UNSPECIFIED_ENTITY,
		PROCESS, UNSPECIFIED_PROCESS, OMITTED_PROCESS, SOURCE, SINK, PERTURBING_AGENT,
		PHENOTYPE, SUBMAP, OR_OP, AND_OP, NOT_OP, TAG, UOI, STATE_DESCN, PRODUCTION_ARC,
		CONSUMPTION_ARC, MODULATION_ARC, STIMULATION_ARC, CATALYSIS_ARC, INHIBITION_ARC,
		NECESSARY_STIMULATION_ARC, LOGIC_ARC, EQUIVALENCE_ARC, CARDINALITY, MATERIAL_TYPE,
		MAP_DIAGRAM, ASSOCIATION, DISOCCIATION, CONCEPTUAL_TYPE, PHYSICAL_CHARACTISTIC
	}

	TreeTokenType getType();
	
	IDrawingElement getElement();

	<T extends IDrawingElement> T getTypedElement();
}
